static final int SCREENX = 1920;//Screen x dimension
static final int SCREENY = 1080;//Screen y dimension
static final int MARGIN = 10;//A margin constant used in graphs
static final int EVENT_NULL = 0;//For a widget that has no event
static final int TEXT_WIDGET=1;//For a search bar
static final int EVENT_BUTTON_SEARCH=1;//For search button.
static final int EVENT_BUTTON_BACK=2;//For back button
//static final int EVENT_DEF_Q = 3;//Previously used to display a default query.
static final int EVENT_USER_WIDGET = 4;//For User Widget (ScrollBox of type user)
static final int EVENT_BUSINESS_WIDGET = 5;//For Business Widget (ScrollBox of type business)
static final int EVENT_REVIEW_WIDGET = 6;//For Review Widget (ScrollBox of type review)
static final int EVENT_SEARCH_USER = 7;//For searching by user (radio button)
static final int EVENT_SEARCH_BUSINESS = 8;//For searching by business (radio button)
static final int EVENT_HOME = 9;//Home button pressed
static final int EVENT_AVE_STARS = 10;//For sorting by average stars (radio button)
static final int EVENT_REV_COUNT = 11;//For sorting by review count
static final int GOOGLE_SEARCH = 12;//For google search button.
static final int EVENT_SHOW_ALL_REVIEWS = 13;//For displaying list of all reviews.
static final int WIDGET_TEXT_Y_OFFSET = -10;//For aligning widget text.
static final int WIDGET_TEXT_X_OFFSET = 10;//For aligning widget text.
static final int BUSINESS_MAP_X = 1050;//Business map x location
static final int BUSINESS_MAP_Y = 100;//Business map y location
static final int BUSINESS_MAP_HEIGHT = 600;//Business map height
static final int BUSINESS_MAP_WIDTH = 600;//Business map width
static final int BUSINESS_MAP_ZOOM = 10;//Business map zoom level
static final int USA_MAP_X = 605;//USA map x location
static final int USA_MAP_Y = 10;//USA map y location
static final int USA_MAP_HEIGHT = 500;//USA map height
static final int USA_MAP_WIDTH = 700;//USA map width
static final int USA_MAP_ZOOM = 5;//USA map zoom level
static final int USA_MAP_CENTRE_X= 40;//USA map centre
static final int USA_MAP_CENTRE_Y= -97;//USA map centre
static final String COOLEST_REVIEW="Coolest Review";//String for coolest review (user screen)
static final String FUNNIEST_REVIEW="Coolest Review";//String for funniest review (user screen)
static final String MOST_USEFUL_REVIEW="Most Useful Review";//String for most useful review (user & business screen)
static final String HIGHEST_REVIEW="Highest Review";//String for highest review (business screen)
static final String LOWEST_REVIEW="lowest Review";//String for lowest review (business screen)
static final int NUM_OF_BUSINESSES_TO_GET = 200;//Max number of businesses to return when searching by name.
static final int NUM_OF_USERS_TO_GET = 200;//Max number of users to return when searching by name.